# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default 
  adapter: postgresql
  host: postgres.ck2bnvbxu3mp.us-west-2.rds.amazonaws.com
  port: 5432
  database: postgres
  user: postgres
  password: postgres
  schema_search_path: "contacts"
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  host: postgres.ck2bnvbxu3mp.us-west-2.rds.amazonaws.com
  port: 5432
  database: postgres
  user: postgres
  password: postgres
  schema_search_path: "contacts"
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: postgres.ck2bnvbxu3mp.us-west-2.rds.amazonaws.com
  port: 5432
  database: postgres
  user: postgres
  password: postgres
  schema_search_path: "contacts_test"

production:
  adapter: postgresql
  host: postgres.ck2bnvbxu3mp.us-west-2.rds.amazonaws.com
  port: 5432
  database: postgres
  user: postgres
  password: postgres
  schema_search_path: "contacts_stage"
